/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
	id("org.springframework.boot") version "2.5.4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
    //
    implementation("org.springframework.boot:spring-boot-starter-web:2.5.4")
    
    implementation("org.springframework.kafka:spring-kafka:2.8.0")
    implementation("org.apache.kafka:kafka-clients:2.8.0")
    
    implementation("org.springframework.boot:spring-boot-starter-websocket:2.5.4")
    implementation("org.springframework:spring-messaging:5.3.10")
    
    implementation("org.springframework.boot:spring-boot-starter-data-redis:2.5.4")
          
    
	implementation("redis.clients:jedis:3.7.0")         
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(19))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.smartconsultor.business.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
