/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smartconsultor.websocket;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
