name: smartconsultor
description: smart consultor project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  # Service locator
  get_it: ^7.6.4
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programing thingies 
  dartz: ^0.10.1
  # Remote API
  connectivity_plus: ^5.0.2
  http: ^0.13.6
  # Local cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  responsive_framework: ^1.1.1 
  flutter_dotenv: ^5.1.0
  parse_server_sdk: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2  
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/