name: smartconsultor
description: smart consultor project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.6.4
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programing thingies
  dartz: ^0.10.1
  # Remote API
  connectivity: ^3.0.6
  http: ^1.1.2
  # Local cache
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
