/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smartconsultor.business;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import com.smartconsultor.business.App;

class AppTest {

}
