apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: gateway
      version: v1      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1      
  template:
    metadata:
      labels:
        app: gateway
        version: v1
        cluster: clustered-app
    spec:
      containers:
        - name: gateway
          image: tuantahp/gateway:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true -Dvertx.jgroups.config=default-configs/default-jgroups-kubernetes.xml -Djgroups.dns.query=clustered-app.default.svc.cluster.local -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory  -agentlib:jdwp=transport=dt_socket,server=y,address=5006,suspend=n,quiet=y"
          ports:
            - containerPort: 31862
            - containerPort: 7800
            - containerPort: 5006 # JDWP port
          livenessProbe:
            httpGet:
              path: /health
              port: 31862
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 31862
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /readiness
              port: 31862
            failureThreshold: 30
            periodSeconds: 10          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment-v2
  labels:
    app: gateway
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: gateway
      version: v2      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1      
  template:
    metadata:
      labels:
        app: gateway
        version: v2
        cluster: clustered-app
    spec:
      containers:
        - name: gateway
          image: tuantahp/gateway:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true -Dvertx.jgroups.config=default-configs/default-jgroups-kubernetes.xml -Djgroups.dns.query=clustered-app.default.svc.cluster.local -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory  -agentlib:jdwp=transport=dt_socket,server=y,address=5006,suspend=n,quiet=y"
          ports:
            - containerPort: 31862
            - containerPort: 7800
            - containerPort: 5006 # JDWP port
          livenessProbe:
            httpGet:
              path: /health
              port: 31862
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 31862
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /readiness
              port: 31862
            failureThreshold: 30
            periodSeconds: 10      
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 31862
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: smartconsultor-certificate-tls
    hosts:
    - "smartconsultor.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-virtualservice
spec:
  hosts:
  - "smartconsultor.com"
  gateways:
  - gateway-gateway
  http:
  - match:
    - uri:
        prefix: /
    - headers:
        version:
          exact: "v1"        
    route:
    - destination:
        host: gateway
        port:
          number: 80
        subset: v1  
  - match:
    - uri:
        prefix: /
    - headers:
        version:
          exact: "v2"        
    route:
    - destination:
        host: gateway
        port:
          number: 80
        subset: v2          
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gateway-service-destination
  namespace: default
spec:
  host: gateway.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10
      tcp:
        maxConnections: 1000
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-keepalive-filter
  namespace: default
spec:
  workloadSelector:
    labels:
      app: gateway
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
      cluster:
        service: gateway.default.svc.cluster.local
    patch:
      operation: MERGE
      value:
        upstream_connection_options:
          tcp_keepalive:
            keepalive_time: 7200         # 2 hours (you can adjust as needed)
            keepalive_interval: 75       # 75 seconds (you can adjust as needed)
            keepalive_probes: 9          # 9 (you can adjust as needed)
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-headers-filter
  namespace: default
spec:
  workloadSelector:
    labels:
      app: my-app
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.router
        config:
          headers_to_add:
          - header:
              key: "version"
              value: "v1"
---
#1.5 Cấu hình retry policy cho các dịch vụ
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: retry-policy
  namespace: istio-system
spec:
  configPatches:
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        name: local_route
        virtual_hosts:
        - name: my-service
          routes:
          - match:
              prefix: "/"
            route:
              retry_policy:
                retry_on: "5xx"
                num_retries: 3
                per_try_timeout: 2s   

---
#2.2.2.3 cho phép gateway truy cập vì gateway tao từ sa default và ns default, nếu bảo mật tạo ra sa mới và gán quyền lại
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: keycloak-authorizationpolicy
  namespace: default
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/default"]
    - source:
        namespaces: ["default"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/*"]
    - operation:
        methods: ["POST"]
        paths: ["/"]                  

  - resourceType: service
    resourceName: keycloak
    namespace: istio-system    
    port: 443 
    localPort: 443    
  - resourceType: service
    resourceName: gateway
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: infinispan
    port: 11222
    localPort: 11222          
  - resourceType: service
    resourceName: superset
    port: 8088
    localPort: 8088
  - resourceType: service
    resourceName: pulsar-pulsar-manager
    port: 9527
    localPort: 9527    
  - resourceType: service
    resourceName: pulsar-grafana
    port: 80
    localPort: 9080        
  - resourceType: service
    resourceName: pulsar-kube-prometheus-sta-prometheus
    port: 9090
    localPort: 9090            
  - resourceType: service
    resourceName: grafana
    namespace: istio-system
    port: 3000
    localPort: 3000                
  - resourceType: service
    resourceName: kiali
    namespace: istio-system
    port: 20001
    localPort: 20001         
  - resourceType: service
    resourceName: tracing
    namespace: istio-system
    port: 80
    localPort: 16686              
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: infinispan-destinationrule
spec:
  host: infinispan
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: superset-destinationrule
spec:
  host: superset
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pulsar-destinationrule
spec:
  host: pulsar-pulsar-manager
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pulsarGrafana-destinationrule
spec:
  host: pulsar-grafana
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pulsarPrometheus-destinationrule
spec:
  host: pulsar-kube-prometheus  
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istioGrafana-destinationrule
spec:
  host: grafana.istio-system.svc.cluster.local 
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali-destinationrule
spec:
  host: kiali.istio-system.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tracing-destinationrule
spec:
  host: tracing.istio-system.svc.cluster.local      

  