apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sc-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: smartconsultor-certificate-tls
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sc-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - sc-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: gateway.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /auth
    route:
    - destination:
        host: keycloak.default.svc.cluster.local
        port:
          number: 80          
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sc-destinationrule
spec:
  host: gateway.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: allow-eventbus
spec:
  hosts:
  - clustered-app.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 7800
    name: tcp
    protocol: TCP
  resolution: NONE

