version: '3'
services:
  controller1:
    image: kraft:latest
    container_name: controller1
    restart: always
    environment:
      KAFKA_CLUSTER_ID: Yclv5fzOT8K3UuIfPP31xg
      KAFKA_ROLE: controller
      KAFKA_ID: 1
      KAFKA_CONTROLLER_FIRST: controller1
      KAFKA_CONTROLLER_SECOND: controller2
      KAFKA_CONTROLLER_THIRD: controller3
    networks:
      - my-network  

  controller2:
    image: kraft:latest
    container_name: controller2
    restart: always
    environment:
      KAFKA_CLUSTER_ID: Yclv5fzOT8K3UuIfPP31xg
      KAFKA_ROLE: controller
      KAFKA_ID: 2
      KAFKA_CONTROLLER_FIRST: controller1
      KAFKA_CONTROLLER_SECOND: controller2
      KAFKA_CONTROLLER_THIRD: controller3
    networks:
      - my-network  

  controller3:
    image: kraft:latest
    container_name: controller3
    restart: always
    environment:
      KAFKA_CLUSTER_ID: Yclv5fzOT8K3UuIfPP31xg
      KAFKA_ROLE: controller
      KAFKA_ID: 3
      KAFKA_CONTROLLER_FIRST: controller1
      KAFKA_CONTROLLER_SECOND: controller2
      KAFKA_CONTROLLER_THIRD: controller3
    networks:
      - my-network  

  broker1:
    image: kraft:latest
    container_name: broker1
    restart: always
    depends_on:
      - controller1
      - controller2
      - controller3
    environment:
      KAFKA_CLUSTER_ID: Yclv5fzOT8K3UuIfPP31xg
      KAFKA_ROLE: broker
      KAFKA_ID: 4
      KAFKA_CONTROLLER_FIRST: controller1
      KAFKA_CONTROLLER_SECOND: controller2
      KAFKA_CONTROLLER_THIRD: controller3    
    networks:
      - my-network

  broker2:
    image: kraft:latest
    container_name: broker2
    restart: always
    depends_on:
      - controller1
      - controller2
      - controller3
    environment:
      KAFKA_CLUSTER_ID: Yclv5fzOT8K3UuIfPP31xg
      KAFKA_ROLE: broker
      KAFKA_ID: 5
      KAFKA_CONTROLLER_FIRST: controller1
      KAFKA_CONTROLLER_SECOND: controller2
      KAFKA_CONTROLLER_THIRD: controller3    
    networks:
      - my-network
      
  broker3:
    image: kraft:latest
    container_name: broker3
    restart: always
    depends_on:
      - controller1
      - controller2
      - controller3
    environment:
      KAFKA_CLUSTER_ID: Yclv5fzOT8K3UuIfPP31xg
      KAFKA_ROLE: broker
      KAFKA_ID: 6
      KAFKA_CONTROLLER_FIRST: controller1
      KAFKA_CONTROLLER_SECOND: controller2
      KAFKA_CONTROLLER_THIRD: controller3    
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
