apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: istio-system
spec:
  secretName: ca-certificate-tls
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  commonName: my-ca
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: istio-system
spec:
  ca:
    secretName: ca-certificate-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smartconsultor-certificate
  namespace: istio-system
spec:
  secretName: smartconsultor-certificate-tls
  duration: 8760h # Thời gian hiệu lực của chứng chỉ
  renewBefore: 360h # Thời gian trước khi hết hạn để gia hạn
  commonName: smartconsultor.com
  dnsNames:
  - smartconsultor.com
  - "*.smartconsultor.com"
  issuerRef:
    name: ca-issuer
    kind: Issuer
