apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: statefulset-reader-role
rules:
  - apiGroups: ["apps"]
    verbs: ["get", "list"]
    resources: ["statefulsets"]
