apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: microservices
build:
  artifacts:
    - image: tuantahp/account
      context: account
      jib:
        project: com.smartconsultor:clustering-kubernetes-account
    - image: tuantahp/gateway
      context: gateway
      jib:
        project: com.smartconsultor:clustering-kubernetes-gateway
manifests:
  rawYaml:
    - account/deployment.yml
    - gateway/deployment.yml
    - gateway/service.yml
    - k8s/headless-service.yml
