apiVersion: v1
kind: Secret
metadata:
  name: cluster-app-user
type: kubernetes.io/basic-auth
data:
  password: c2VjcmV0OTk=
  username: YXBw
---
apiVersion: v1
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: cluster-superuser
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 2
  superuserSecret:
    name: cluster-superuser
  bootstrap:
    initdb:
      database: app
      owner: app
      dataChecksums: true
      encoding: 'UTF8'
      secret:
        name: cluster-app-user  
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard   
  walStorage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduledbackup-postgresql
spec:
  cluster:
    name: postgresql
  schedule: 0 0 0 * * *  
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-rw
spec:
  cluster:
    name: postgresql
  instances: 1
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"    
  type: rw