apiVersion: v1
kind: Pod
metadata:
  name: postgresql-client
spec:
  containers:
  - name: postgresql-client
    image: postgres:latest
    command: ["sleep", "infinity"] # Cho container chạy ở chế độ sleep vô hạn
    tty: true
