version: "3" 
services: 
 
 redis1: 
   image: redis:latest 
   command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes 
   volumes: 
     - ./redis1:/data 
   ports: 
     - "7001:7001" 
 
 redis2: 
   image: redis:latest 
   command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes 
   volumes: 
     - ./redis2:/data 
   ports: 
     - "7002:7002" 
 
 redis3: 
   image: redis:latest 
   command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes 
   volumes: 
     - ./redis3:/data 
   ports: 
     - "7003:7003" 
 
 redis4: 
   image: redis:latest 
   command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes 
   volumes: 
     - ./redis4:/data 
   ports: 
     - "7004:7004" 
 
 redis5: 
   image: redis:latest 
   command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes 
   volumes: 
     - ./redis5:/data 
   ports: 
     - "7005:7005" 
 
 redis6: 
   image: redis:latest 
   command: redis-server --port 7006 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes 
   volumes: 
     - ./redis6:/data 
   ports: 
     - "7006:7006" 
 
 redis-trib: 
   image: redis:latest 
   command: echo yes | redis-cli --cluster create  redis1:7001 redis2:7002 redis3:7003 redis4:7004 redis5:7005 redis6:7006 --cluster-replicas 1 
   depends_on: 
     - redis1 
     - redis2 
     - redis3 
     - redis4 
     - redis5 
     - redis6 
